import type { Chain } from "@/types"

export type ChainAdapterDefinition = {
  id: Chain
  name: string
  language: string
  toolchain: string
  sourceFile: string
  contractNoun: string
  previewAddress: string
  generationReady: boolean
  deploymentReady: boolean
  testNetwork: string
  samplePrompts: string[]
}

export const CHAIN_IDS = ["evm", "solana", "sui", "aptos", "cosmos", "ton", "near", "starknet", "algorand"] as const satisfies readonly Chain[]

export const CHAIN_ADAPTERS: Record<Chain, ChainAdapterDefinition> = {
  evm: {
    id: "evm", name: "EVM", language: "Solidity", toolchain: "solc", sourceFile: "Contract.sol", contractNoun: "Contract",
    previewAddress: "0x0000000000000000000000000000000000000000", generationReady: true, deploymentReady: true, testNetwork: "Sepolia",
    samplePrompts: [
      "Create an ERC-20 token with vesting, a treasury, and a polished transfer dashboard.",
      "Build a crowdfunding contract with milestones, contributor refunds, and a funding dashboard.",
      "Make an NFT membership pass with token-gated voting and renewable access.",
      "Create a multisig treasury with spending proposals, approval thresholds, and execution timelocks.",
      "Build onchain event ticketing with capped supply, controlled resale, royalties, and QR check-in.",
      "Create a USDC subscription marketplace with recurring periods, escrow, and provider withdrawals.",
      "Build a decentralized freelance marketplace with milestone escrow, disputes, and reputation badges.",
      "Create a token-gated content platform with creator subscriptions and revenue sharing.",
      "Build a real-estate fractional ownership vault with compliant transfers and dividend claims.",
      "Create a prediction market with binary outcomes, deadlines, oracle settlement, and claims.",
      "Build a carbon-credit registry with NFT certificates, retirement records, and issuer roles.",
      "Create a lending pool with collateral ratios, interest accrual, liquidations, and a risk dashboard.",
      "Build a recurring payroll contract that streams ERC-20 salaries and supports employee withdrawals.",
      "Create an onchain loyalty program with ERC-1155 rewards, tiers, redemption, and merchant roles.",
      "Build a charity donation vault with campaign allocation, transparent withdrawals, and receipts.",
      "Create a sealed-bid NFT auction with commit-reveal bidding, refunds, and royalty settlement.",
      "Build a decentralized domain registry with expiring names, renewals, and transferable ownership.",
      "Create a supply-chain tracker with role-based checkpoints, product NFTs, and provenance history.",
      "Build an ERC-4626 yield vault with deposits, withdrawals, fees, and share-price reporting.",
      "Create a grant program with applications, quadratic community voting, and milestone payouts.",
      "Build an insurance pool with policy NFTs, premium collection, claims voting, and payouts.",
      "Create a gaming marketplace for ERC-1155 items with listings, bundles, and creator royalties.",
      "Build a token buyback treasury with configurable limits, governance approval, and event history.",
      "Create a decentralized will that releases tokens to beneficiaries after a verified inactivity period.",
      "Build a rotating savings club with scheduled deposits, member turns, penalties, and withdrawals.",
    ],
  },
  solana: {
    id: "solana", name: "Solana", language: "Rust (Anchor)", toolchain: "Anchor + cargo build-sbf", sourceFile: "lib.rs", contractNoun: "Program",
    previewAddress: "11111111111111111111111111111111", generationReady: true, deploymentReady: true, testNetwork: "Devnet",
    samplePrompts: [
      "Build a Solana crowdfunding program with milestones and contributor refunds.",
      "Create an Anchor escrow program for safe peer-to-peer SPL token swaps.",
      "Make a Solana membership program with renewable access and a Phantom interface.",
      "Build an SPL token launchpad using PDAs, a capped mint, and permanent mint-authority revocation.",
      "Create an NFT raffle with verifiable entries, a fixed deadline, and winner-only claiming.",
      "Build a creator tipping vault that accepts SPL tokens and records transparent withdrawals.",
      "Create a Solana NFT ticketing program with compressed assets, resale rules, and check-in.",
      "Build a token vesting program using PDAs, cliff schedules, revocation, and beneficiary claims.",
      "Create a decentralized order book for SPL assets with deposits, matching, and cancellation.",
      "Build a Solana lending vault with collateral accounts, interest, liquidation, and health factors.",
      "Create a DAO treasury program with proposals, vote receipts, quorum, and timelocked execution.",
      "Build an onchain loyalty program with Token Extensions, merchant roles, and reward redemption.",
      "Create a creator subscription program with recurring periods and token-gated content access.",
      "Build a prediction market with outcome vaults, oracle settlement, and proportional claims.",
      "Create a gaming inventory program using compressed NFTs, crafting recipes, and trading.",
      "Build a charitable donation vault with campaign PDAs, transparent accounting, and withdrawals.",
      "Create a sealed-bid auction using commit-reveal instructions and secure bidder refunds.",
      "Build a payroll program that streams SPL token salaries and supports partial employee claims.",
      "Create a launchpad with allowlists, per-wallet limits, vesting, and unsold-token recovery.",
      "Build a bounty board with funded task PDAs, submissions, reviewer approval, and payouts.",
      "Create a domain registry with renewable names, ownership transfers, and reverse resolution.",
      "Build a pooled savings program with scheduled contributions, member turns, and penalties.",
      "Create a carbon-credit registry using compressed NFTs and permanent retirement records.",
      "Build a referral rewards program with deterministic PDAs and claimable SPL commissions.",
      "Create a sports tournament pool with entry fees, bracket results, and winner distributions.",
    ],
  },
  sui: {
    id: "sui", name: "Sui", language: "Move", toolchain: "Sui CLI + @mysten/sui", sourceFile: "sources/main.move", contractNoun: "Package",
    previewAddress: "0x0", generationReady: true, deploymentReady: process.env.NEXT_PUBLIC_SUI_DEPLOYMENT_ENABLED === "true", testNetwork: "Sui Testnet",
    samplePrompts: [
      "Build a Sui Move marketplace for owned digital objects.",
      "Create a Sui loyalty asset with an admin capability and transfers.",
      "Build a shared-object crowdfunding app on Sui.",
      "Create event ticket objects with controlled resale and kiosk-based check-in.",
      "Build a shared treasury object with capability-based proposals, voting, and withdrawals.",
      "Create composable game inventory objects that players can craft, upgrade, and trade.",
      "Build a Sui kiosk marketplace with royalties, listings, purchases, and creator controls.",
      "Create a vesting vault object with cliff schedules, beneficiary claims, and revocation capability.",
      "Build a lending protocol with shared pools, collateral objects, liquidations, and health checks.",
      "Create a DAO using shared proposal objects, voting receipts, quorum, and execution capabilities.",
      "Build a subscription pass object with renewals, expiration checks, and merchant settlement.",
      "Create a prediction market with shared outcome pools and oracle-authorized settlement.",
      "Build a supply-chain system with dynamic fields, product objects, and signed checkpoints.",
      "Create a raffle with ticket objects, verifiable randomness, deadlines, and winner claims.",
      "Build an escrow exchange for coins and objects with buyer confirmation and timeout refunds.",
      "Create a creator royalty splitter with programmable transaction blocks and claimable balances.",
      "Build a charitable campaign with shared funding objects, milestones, and donor refunds.",
      "Create a token launchpad with TreasuryCap controls, allowlists, and per-wallet limits.",
      "Build a bounty board with task objects, funded rewards, submissions, and reviewer capabilities.",
      "Create a domain-name object registry with renewals, transfers, and reverse lookup.",
      "Build a pooled savings club with member capabilities, scheduled contributions, and payouts.",
      "Create a carbon-credit asset with issuer capability, provenance, and irreversible retirement.",
      "Build a tournament app with entry objects, bracket updates, and prize distribution.",
      "Create an insurance pool with policy objects, claims review, voting, and settlement.",
      "Build a referral program with immutable referral links and claimable coin rewards.",
    ],
  },
  aptos: {
    id: "aptos", name: "Aptos", language: "Move", toolchain: "Aptos CLI + @aptos-labs/ts-sdk", sourceFile: "sources/main.move", contractNoun: "Module",
    previewAddress: "0x0", generationReady: true, deploymentReady: process.env.NEXT_PUBLIC_APTOS_DEPLOYMENT_ENABLED === "true", testNetwork: "Aptos Devnet",
    samplePrompts: [
      "Create an Aptos Move membership module using objects.",
      "Build an Aptos crowdfunding module with refunds.",
      "Create an Aptos fungible asset treasury with role controls.",
      "Build event ticketing with Digital Assets, capped issuance, and transfer restrictions.",
      "Create a marketplace escrow using resource accounts and buyer-confirmed settlement.",
      "Build loyalty points with a soulbound customer profile and auditable reward records.",
      "Create a vesting module with resource accounts, cliff schedules, and beneficiary claims.",
      "Build a DAO treasury with proposal objects, delegated voting, quorum, and delayed execution.",
      "Create a prediction market with separate outcome stores and oracle-authorized resolution.",
      "Build a lending pool with collateral resources, interest indexes, and liquidation rules.",
      "Create an NFT raffle with verifiable randomness, ticket objects, and winner claiming.",
      "Build a creator subscription module with renewable passes and revenue distribution.",
      "Create a supply-chain tracker with Digital Assets and role-authorized checkpoints.",
      "Build a payroll vault for Fungible Assets with vesting, streaming, and employee claims.",
      "Create a sealed-bid auction using commit-reveal entries and automatic loser refunds.",
      "Build a charity campaign with milestone approvals, donor receipts, and refund conditions.",
      "Create a token launchpad with allowlists, per-account limits, and unsold asset recovery.",
      "Build a bounty marketplace with funded task objects, submissions, reviews, and payouts.",
      "Create a naming service with expiring registrations, renewals, transfers, and reverse records.",
      "Build a pooled savings club with member resources, scheduled deposits, and rotating payouts.",
      "Create an insurance pool with policy objects, premium accounting, claims, and settlement.",
      "Build a carbon-credit registry with issuer roles, Digital Asset certificates, and retirement.",
      "Create a referral rewards module with immutable attribution and claimable commissions.",
      "Build a tournament prize pool with registrations, authorized results, and winner claims.",
      "Create a decentralized credential registry with issuer capabilities and revocable attestations.",
    ],
  },
  cosmos: {
    id: "cosmos", name: "CosmWasm", language: "Rust", toolchain: "cargo wasm + CosmJS", sourceFile: "src/lib.rs", contractNoun: "Contract",
    previewAddress: "cosmos1preview", generationReady: true, deploymentReady: false, testNetwork: "Configured CosmWasm testnet",
    samplePrompts: [
      "Build a CosmWasm escrow contract with expiry and refunds.",
      "Create a CW20 token vesting contract.",
      "Build a CosmWasm DAO proposal and voting contract.",
      "Create CW721 event tickets with controlled transfers and an organizer check-in flow.",
      "Build a subscription vault with block-height renewals, grace periods, and cancellations.",
      "Create a token-gated community registry using CW20 and CW721 balance queries.",
      "Build a CW721 marketplace with fixed-price listings, royalties, expiry, and withdrawals.",
      "Create a multisig treasury with proposal deposits, voting thresholds, and execution delays.",
      "Build a crowdfunding factory that instantiates isolated campaigns with milestone refunds.",
      "Create a prediction market with oracle settlement, outcome shares, and claim distribution.",
      "Build a CW20 staking vault with reward indexes, lock periods, and emergency unstaking.",
      "Create a vesting contract with cliffs, linear release, revocation, and beneficiary claims.",
      "Build an interchain donation app using IBC transfers and transparent campaign accounting.",
      "Create a DAO payroll contract with recurring CW20 payments and cancellable streams.",
      "Build a raffle using chain randomness, ticket limits, deadlines, and winner claims.",
      "Create a supply-chain registry with authorized actors and immutable product checkpoints.",
      "Build a bounty board with funded tasks, submissions, reviewer approval, and CW20 payouts.",
      "Create a naming service with expiring registrations, renewals, ownership, and reverse records.",
      "Build a pooled savings club with scheduled deposits, rotating recipients, and penalties.",
      "Create an insurance mutual with membership, premiums, claims voting, and payouts.",
      "Build a carbon-credit CW721 collection with issuer roles and irreversible retirement.",
      "Create a token launchpad with allowlists, purchase limits, vesting, and fund recovery.",
      "Build a tournament pool with entry fees, authorized outcomes, and prize distribution.",
      "Create a decentralized credential registry with issuers, expirations, and revocations.",
      "Build a revenue-sharing splitter for CW20 and native tokens with claimable balances.",
    ],
  },
  ton: {
    id: "ton", name: "TON", language: "Tact", toolchain: "Tact/Acton + @ton/core", sourceFile: "contracts/main.tact", contractNoun: "Contract",
    previewAddress: "EQPreview", generationReady: true, deploymentReady: false, testNetwork: "TON Testnet",
    samplePrompts: [
      "Create a TON subscription contract in Tact.",
      "Build a TON escrow contract with timeout refunds.",
      "Create a TON Jetton-based membership app.",
      "Build a TON crowdfunding contract with milestone voting and contributor refunds.",
      "Create an NFT ticket collection with ownership checks and organizer check-in.",
      "Build Jetton staking with transparent reward accounting and emergency withdrawals.",
      "Create a TON NFT marketplace with listings, royalties, purchase settlement, and cancellation.",
      "Build a vesting contract in Tact with cliffs, linear release, and beneficiary claims.",
      "Create a DAO treasury with proposals, weighted voting, quorum, and delayed execution.",
      "Build a prediction market with oracle resolution, outcome stakes, and proportional claims.",
      "Create a creator tipping contract supporting TON and Jettons with withdrawal records.",
      "Build a token launchpad with allowlists, wallet limits, and Jetton distribution.",
      "Create a raffle with numbered tickets, a deadline, verifiable randomness, and winner claims.",
      "Build a bounty board with funded tasks, submissions, approvals, and Jetton payouts.",
      "Create a domain registry with expiring names, renewal fees, and transferable ownership.",
      "Build a payroll contract with scheduled Jetton payments and employee withdrawals.",
      "Create a charity campaign with milestones, transparent funding, and donor refunds.",
      "Build a pooled savings club with scheduled deposits, participant turns, and penalties.",
      "Create a supply-chain registry with authorized checkpoints and immutable product history.",
      "Build an insurance mutual with premiums, policy records, claim voting, and settlement.",
      "Create a carbon-credit NFT collection with issuer authorization and permanent retirement.",
      "Build a tournament prize pool with registrations, signed results, and winner payouts.",
      "Create a referral rewards contract with immutable attribution and claimable Jettons.",
      "Build a multisig treasury with approval thresholds, replay protection, and transfer limits.",
      "Create an onchain credential registry with trusted issuers, expiration, and revocation.",
    ],
  },
  near: {
    id: "near", name: "NEAR", language: "Rust", toolchain: "cargo near + near-api-js", sourceFile: "src/lib.rs", contractNoun: "Contract",
    previewAddress: "preview.testnet", generationReady: true, deploymentReady: false, testNetwork: "NEAR Testnet",
    samplePrompts: [
      "Build a NEAR crowdfunding contract with storage accounting.",
      "Create a NEAR membership contract with renewable access.",
      "Build a NEAR escrow contract with promise-safe callbacks.",
      "Create NFT event ticketing with storage deposits, controlled resale, and check-in.",
      "Build a fungible-token vesting vault that follows NEP standards and supports revocation.",
      "Create a DAO treasury with proposals, quorum voting, and cross-contract payouts.",
      "Build an NFT marketplace following NEP standards with listings, royalties, and storage deposits.",
      "Create a linear vesting contract for fungible tokens with cliffs and beneficiary claims.",
      "Build a prediction market with oracle callbacks, outcome balances, and safe settlement.",
      "Create a token launchpad with allowlists, account limits, vesting, and refund support.",
      "Build a staking vault with reward indexes, lock periods, and storage-cost accounting.",
      "Create a creator tipping app supporting NEAR and fungible tokens with withdrawal history.",
      "Build a raffle with ticket deposits, verifiable randomness, deadlines, and winner claims.",
      "Create a bounty board with funded tasks, submissions, reviews, and cross-contract payouts.",
      "Build a naming service with subaccounts, expiring registrations, renewals, and transfers.",
      "Create a payroll contract with streamed fungible-token salaries and cancellable schedules.",
      "Build a charity platform with milestones, donor receipts, transparent accounting, and refunds.",
      "Create a pooled savings club with scheduled deposits, rotating payouts, and penalties.",
      "Build a supply-chain registry with authorized roles and immutable product checkpoints.",
      "Create an insurance mutual with premium deposits, claims voting, and settlement.",
      "Build a carbon-credit NFT registry with authorized issuers and irreversible retirement.",
      "Create a tournament pool with entry deposits, authorized results, and prize claims.",
      "Build a referral rewards contract with persistent attribution and fungible-token commissions.",
      "Create a multisig treasury with proposal approvals, execution delays, and transfer limits.",
      "Build a decentralized credential registry with trusted issuers, expiry, and revocation.",
    ],
  },
  starknet: {
    id: "starknet", name: "Starknet", language: "Cairo", toolchain: "Scarb + Starknet Foundry", sourceFile: "src/lib.cairo", contractNoun: "Contract",
    previewAddress: "0x0", generationReady: true, deploymentReady: false, testNetwork: "Starknet Sepolia",
    samplePrompts: [
      "Create a Starknet Cairo crowdfunding contract.",
      "Build a Starknet token vesting contract with role controls.",
      "Create a Starknet NFT membership contract.",
      "Build an ERC-20 streaming-payments contract in Cairo with pause and cancellation controls.",
      "Create a marketplace escrow with typed events and an account-abstraction-friendly interface.",
      "Build a DAO treasury with delegated voting, quorum, and a proposal execution timelock.",
      "Create an ERC-721 marketplace in Cairo with listings, royalties, and escrowed settlement.",
      "Build an overcollateralized lending pool with interest indexes and liquidation checks.",
      "Create a prediction market with oracle resolution, outcome shares, and claimable winnings.",
      "Build a Cairo raffle with ticket limits, verifiable randomness, and winner claiming.",
      "Create a creator subscription contract with renewable access and revenue splitting.",
      "Build an onchain loyalty system with ERC-1155 rewards, tiers, and merchant permissions.",
      "Create a token launchpad with allowlists, account-abstraction support, and vesting.",
      "Build a bounty board with funded tasks, reviewer approval, and ERC-20 payouts.",
      "Create a naming service with expiring registrations, renewals, and reverse records.",
      "Build a payroll contract with ERC-20 salary streams and cancellable schedules.",
      "Create a charity campaign with milestones, contributor receipts, and conditional refunds.",
      "Build a pooled savings club with scheduled deposits, rotating payouts, and penalties.",
      "Create a supply-chain registry with role-based checkpoints and immutable event history.",
      "Build an insurance mutual with policy NFTs, premiums, claims voting, and settlement.",
      "Create a carbon-credit NFT registry with issuer roles and irreversible retirement.",
      "Build a tournament pool with entry fees, signed results, and winner distributions.",
      "Create a referral program with permanent attribution and claimable token commissions.",
      "Build a multisig account treasury with thresholds, nonce protection, and spending limits.",
      "Create a decentralized credential registry with trusted issuers and revocable attestations.",
    ],
  },
  algorand: {
    id: "algorand", name: "Algorand", language: "Algorand Python", toolchain: "PuyaPy + AlgoKit", sourceFile: "smart_contracts/main/contract.py", contractNoun: "Application",
    previewAddress: "0", generationReady: true, deploymentReady: false, testNetwork: "Algorand Testnet",
    samplePrompts: [
      "Build an Algorand crowdfunding application with refunds.",
      "Create an Algorand membership application using box storage.",
      "Build an Algorand escrow application with grouped transactions.",
      "Create an ASA launchpad with opt-in checks, capped distribution, and clawback disabled.",
      "Build a ticketing application using boxes and atomic transactions for secure check-in.",
      "Create a time-based subscription app with renewal receipts and an ARC-compatible frontend.",
      "Build an ASA staking application with reward indexes, lock periods, and safe opt-out handling.",
      "Create an NFT marketplace using atomic transfers, listing boxes, royalties, and cancellation.",
      "Build a vesting application with cliff schedules, linear release, and beneficiary claims.",
      "Create a DAO treasury with proposal boxes, weighted voting, quorum, and delayed execution.",
      "Build a prediction market using oracle-signed outcomes and proportional prize claims.",
      "Create a creator tipping app supporting ALGO and ASAs with transparent withdrawals.",
      "Build a raffle using VRF randomness, ticket limits, deadlines, and winner settlement.",
      "Create a bounty board with funded task boxes, submissions, reviews, and atomic payouts.",
      "Build a naming service with box-based records, renewals, transfers, and reverse lookup.",
      "Create a payroll application with scheduled ASA payments and employee claim transactions.",
      "Build a charity platform with milestones, donor receipts, and conditional group refunds.",
      "Create a pooled savings club with scheduled deposits, rotating recipients, and penalties.",
      "Build a supply-chain tracker with authorized accounts and immutable product checkpoints.",
      "Create an insurance mutual with premium deposits, claims voting, and atomic settlement.",
      "Build a carbon-credit ASA registry with issuer roles and permanent retirement records.",
      "Create a tournament pool with entry payments, authorized results, and prize distribution.",
      "Build a referral rewards application with immutable attribution and claimable ASA rewards.",
      "Create a multisig-governed treasury with spending proposals and enforced daily limits.",
      "Build a decentralized credential registry with trusted issuers, expiration, and revocation.",
    ],
  },
}

export function getChainAdapter(chain: Chain) {
  return CHAIN_ADAPTERS[chain]
}

export function isChain(value: unknown): value is Chain {
  return typeof value === "string" && CHAIN_IDS.includes(value as Chain)
}
