import type { Dapp } from "@/types"

export const featuredDapps: Dapp[] = [
  {
    id: "liquid-stake",
    name: "LiquidStake",
    description: "Liquid staking protocol with instant unstaking and automated validator selection.",
    chain: "evm",
    tags: ["DeFi", "Staking"],
    owner: "0x7A2...91F",
    icon: "L",
    accent: "blue",
    isFeatured: true,
  },
  {
    id: "pixel-punks",
    name: "Pixel Punks",
    description: "Generative on-chain NFT collection with community-governed traits and royalties.",
    chain: "solana",
    tags: ["NFT", "Community"],
    owner: "Gk4v...d2Q",
    icon: "P",
    accent: "purple",
    isFeatured: true,
  },
  {
    id: "based-dao",
    name: "BasedDAO",
    description: "A lightweight governance suite for creating proposals, voting, and managing treasuries.",
    chain: "evm",
    tags: ["DAO", "Governance"],
    owner: "0x3F9...C21",
    icon: "B",
    accent: "cyan",
    isFeatured: true,
  },
  {
    id: "stream-pay",
    name: "StreamPay",
    description: "Token vesting and real-time payroll streams for web3 teams and contributors.",
    chain: "solana",
    tags: ["Payments", "Tools"],
    owner: "An8m...q7L",
    icon: "S",
    accent: "green",
  },
  {
    id: "safe-vault",
    name: "SafeVault",
    description: "Multi-signature asset vault with configurable timelocks and recovery guardians.",
    chain: "evm",
    tags: ["Security", "Wallet"],
    owner: "0x91B...D08",
    icon: "V",
    accent: "orange",
  },
  {
    id: "proof-pass",
    name: "ProofPass",
    description: "Token-gated memberships with private attestations and portable credentials.",
    chain: "evm",
    tags: ["Identity", "Social"],
    owner: "0x42C...8A1",
    icon: "P",
    accent: "pink",
  },
]
